# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd27c37c00363bee103e0d88cebe528cc8d251c05efb91fb3ea189038354dcaae88fe68a7e395f441de16b0cc8a006f84e7d8f5373f206ff3c5ed770f86fe7c8

test:
  secret_key_base: 08f7110e57e276bf5ccb24ffa66b902b4dd00cd7d46824379c3acbc58838fa18d71d4b1ab7e8006ed124cf1f52b355b1c38c261264bf2bb4eb8d0e10470e1386

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
